language: node_js
node_js:
  - "0.10"
env:
  global:
  - secure: SA2ZSqSCDXiQsD3qyCitYe4CU9fF6bgj/I85Xh4rRFv9yGtqQVAFkE6OF4zUn6BalF4rU0ye5ispRJNlAgg4O7GYVvMCVRAj9CRtr+JvrGQYPRAaMhTxk6nDvG3AIKIBG2dNutzgPWQygOw0u/PVNpLHq/w165Jngs0TMJx58o4=
  - secure: ARzhpKxSK5fMARXm4+jpG7GpqzeFUKWFyt5pFW83tXHj8Njr8LRinbjs5x8cuLAuB/m8JFKrEecsTF1jQuS7wJ/lnfLyP56e6u8rqLoaHGGCeEpTE+TdZmwRXh7TT5m+N1alR5dgLEdDofiH6Cxp7w7/I5xLc2lp/sz/281XMMs=