ui: mocha-bdd
scripts:
  - "build/lazyload.min.js"
  - "components/in-viewport/test/helpers/assert.js"
  - "components/in-viewport/test/helpers/helper.js"
  - "test/helpers/helper.js"
server:
  - ./test/fixtures/serve.js
browsers:
  - name: chrome
    version: 27..latest
  - name: firefox
    version: 25..latest
  - name: ie
    version: 8..latest
